import type { Direction, LevelDefinition } from "../game";

export interface TutorialLevel extends LevelDefinition {
  lesson: string;
}

export const tutorialLevels = [
  {
    id: "tutorial-01-first-push",
    title: "First Push",
    lesson: "Push a crate onto a receiver pad.",
    description: "A compact baseline puzzle for movement and box pushing.",
    worlds: [{ id: "root", name: "Lab Floor", width: 6, height: 5 }],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      { id: "crate", type: "box", name: "Crate", position: { worldId: "root", x: 2, y: 2 } },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 4, y: 2 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-02-step-inside",
    title: "Step Inside",
    lesson: "Enter an open crate world.",
    description: "The player target sits inside the crate's inner world.",
    worlds: [
      { id: "root", name: "Outer Bench", width: 5, height: 5 },
      {
        id: "inside-alpha",
        name: "Inside Alpha",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "box-alpha" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-alpha",
        type: "box",
        name: "Alpha",
        open: true,
        innerWorldId: "inside-alpha",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "inner-goal",
        type: "goal",
        target: "player",
        position: { worldId: "inside-alpha", x: 1, y: 1 },
      },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-03-load-the-crate",
    title: "Load the Crate",
    lesson: "Push one crate into another open crate.",
    description: "A crate can transfer into the open crate's inner world.",
    worlds: [
      { id: "root", name: "Loading Rail", width: 5, height: 5 },
      {
        id: "inside-loader",
        name: "Loader Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "loader" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 0, y: 2 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "loader",
        type: "box",
        name: "Loader",
        open: true,
        innerWorldId: "inside-loader",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "inner-goal",
        type: "goal",
        target: "box",
        position: { worldId: "inside-loader", x: 1, y: 1 },
      },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-04-push-out",
    title: "Push Out",
    lesson: "Push cargo out from an inner world to its parent.",
    description: "The parent-world target sits beside the containing crate.",
    worlds: [
      { id: "root", name: "Parent Track", width: 5, height: 5 },
      {
        id: "inside-exit",
        name: "Exit Chamber",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "exit-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "inside-exit", x: 1, y: 1 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "inside-exit", x: 2, y: 1 } },
      {
        id: "exit-box",
        type: "box",
        name: "Exit Box",
        open: true,
        innerWorldId: "inside-exit",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 3, y: 2 } },
    ],
    playerId: "player",
    activeWorldId: "inside-exit",
  },
  {
    id: "tutorial-05-two-layer-transfer",
    title: "Two-Layer Transfer",
    lesson: "Enter a crate, then load cargo into a deeper crate.",
    description: "A two-level setup introduces nested interior previews.",
    worlds: [
      { id: "root", name: "Outer Rig", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "Fold A",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 2 },
      },
      {
        id: "inside-b",
        name: "Fold B",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-a",
        type: "box",
        name: "Fold A",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "inside-a", x: 2, y: 2 } },
      {
        id: "box-b",
        type: "box",
        name: "Fold B",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 3, y: 2 },
      },
      { id: "deep-goal", type: "goal", target: "box", position: { worldId: "inside-b", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-06-nested-cargo",
    title: "Nested Cargo",
    lesson: "Push a world-bearing crate into an open crate.",
    description: "The moved crate keeps its own interior after it enters a dock crate.",
    worlds: [
      { id: "root", name: "Dock Rail", width: 5, height: 5 },
      {
        id: "portable-inner",
        name: "Portable Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "portable" },
        entry: { x: 1, y: 1 },
      },
      {
        id: "dock-inner",
        name: "Dock Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "dock" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 0, y: 2 } },
      {
        id: "portable",
        type: "box",
        name: "Portable",
        innerWorldId: "portable-inner",
        position: { worldId: "root", x: 1, y: 2 },
      },
      {
        id: "dock",
        type: "box",
        name: "Dock",
        open: true,
        innerWorldId: "dock-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "dock-goal", type: "goal", target: "box", position: { worldId: "dock-inner", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-07-out-to-receiver",
    title: "Out to Receiver",
    lesson: "Push cargo out of one crate and directly into another.",
    description: "A push-out can hand cargo to a neighboring open receiver.",
    worlds: [
      { id: "root", name: "Receiver Line", width: 5, height: 5 },
      {
        id: "exit-inner",
        name: "Exit Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "exit-box" },
        entry: { x: 1, y: 1 },
      },
      {
        id: "receiver-inner",
        name: "Receiver Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "receiver" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "exit-inner", x: 1, y: 1 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "exit-inner", x: 2, y: 1 } },
      {
        id: "exit-box",
        type: "box",
        name: "Exit Box",
        open: true,
        innerWorldId: "exit-inner",
        position: { worldId: "root", x: 1, y: 2 },
      },
      {
        id: "receiver",
        type: "box",
        name: "Receiver",
        open: true,
        innerWorldId: "receiver-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "receiver-goal", type: "goal", target: "box", position: { worldId: "receiver-inner", x: 1, y: 1 } },
    ],
    playerId: "player",
    activeWorldId: "exit-inner",
  },
  {
    id: "tutorial-08-chain-push",
    title: "Chain Push",
    lesson: "Push a short crate chain without losing alignment.",
    description: "This tests ordinary Sokoban pressure before deeper recursion.",
    worlds: [{ id: "root", name: "Chain Lane", width: 6, height: 5 }],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 0, y: 2 } },
      { id: "crate-a", type: "box", name: "A", position: { worldId: "root", x: 1, y: 2 } },
      { id: "crate-b", type: "box", name: "B", position: { worldId: "root", x: 2, y: 2 } },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 4, y: 2 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-09-left-exit",
    title: "Left Exit",
    lesson: "Push cargo out through the opposite edge.",
    description: "Push-out works in directions other than right.",
    worlds: [
      { id: "root", name: "Return Track", width: 5, height: 5 },
      {
        id: "return-inner",
        name: "Return Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "return-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "return-inner", x: 1, y: 1 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "return-inner", x: 0, y: 1 } },
      {
        id: "return-box",
        type: "box",
        name: "Return Box",
        open: true,
        innerWorldId: "return-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 1, y: 2 } },
    ],
    playerId: "player",
    activeWorldId: "return-inner",
  },
  {
    id: "tutorial-10-deep-entry",
    title: "Deep Entry",
    lesson: "Navigate from the root into a second nested world.",
    description: "A final navigation lesson before broader content expansion.",
    worlds: [
      { id: "root", name: "Outer Gate", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "First Fold",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 2 },
      },
      {
        id: "inside-b",
        name: "Second Fold",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-a",
        type: "box",
        name: "First Fold",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "box-b",
        type: "box",
        name: "Second Fold",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 2, y: 2 },
      },
      { id: "deep-goal", type: "goal", target: "player", position: { worldId: "inside-b", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-11-north-exit",
    title: "North Exit",
    lesson: "Push cargo out through the top edge.",
    description: "The parent receiver is above the containing crate.",
    worlds: [
      { id: "root", name: "North Rail", width: 5, height: 5 },
      {
        id: "north-inner",
        name: "North Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "north-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "north-inner", x: 1, y: 1 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "north-inner", x: 1, y: 0 } },
      {
        id: "north-box",
        type: "box",
        name: "North Box",
        open: true,
        innerWorldId: "north-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 2, y: 1 } },
    ],
    playerId: "player",
    activeWorldId: "north-inner",
  },
  {
    id: "tutorial-12-south-exit",
    title: "South Exit",
    lesson: "Push cargo out through the bottom edge.",
    description: "The parent receiver is below the containing crate.",
    worlds: [
      { id: "root", name: "South Rail", width: 5, height: 5 },
      {
        id: "south-inner",
        name: "South Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "south-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "south-inner", x: 1, y: 1 } },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "south-inner", x: 1, y: 2 } },
      {
        id: "south-box",
        type: "box",
        name: "South Box",
        open: true,
        innerWorldId: "south-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 2, y: 3 } },
    ],
    playerId: "player",
    activeWorldId: "south-inner",
  },
  {
    id: "tutorial-13-inside-to-outside",
    title: "Inside-to-Outside",
    lesson: "Enter a crate, then push cargo back to the root.",
    description: "Entry and exit combine into one short recursive route.",
    worlds: [
      { id: "root", name: "Root Return", width: 5, height: 5 },
      {
        id: "return-inner",
        name: "Return Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "return-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "return-box",
        type: "box",
        name: "Return Box",
        open: true,
        innerWorldId: "return-inner",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "return-inner", x: 2, y: 1 } },
      { id: "goal", type: "goal", target: "box", position: { worldId: "root", x: 3, y: 2 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-14-vertical-loader",
    title: "Vertical Loader",
    lesson: "Load cargo downward inside an entered crate.",
    description: "The same push-into idea works vertically.",
    worlds: [
      { id: "root", name: "Vertical Gate", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "Vertical Fold",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 1 },
      },
      {
        id: "inside-b",
        name: "Lower Fold",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 1 } },
      {
        id: "box-a",
        type: "box",
        name: "Vertical Fold",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 1 },
      },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "inside-a", x: 1, y: 2 } },
      {
        id: "box-b",
        type: "box",
        name: "Lower Fold",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 1, y: 3 },
      },
      { id: "goal", type: "goal", target: "box", position: { worldId: "inside-b", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-15-deep-egress",
    title: "Deep Egress",
    lesson: "Enter two layers and push cargo out of the deeper one.",
    description: "The final tutorial links navigation and push-out across two folds.",
    worlds: [
      { id: "root", name: "Deep Rig", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "First Chamber",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 2 },
      },
      {
        id: "inside-b",
        name: "Second Chamber",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-a",
        type: "box",
        name: "First Chamber",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "box-b",
        type: "box",
        name: "Second Chamber",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 2, y: 2 },
      },
      { id: "crate", type: "box", name: "Cargo", position: { worldId: "inside-b", x: 2, y: 1 } },
      { id: "goal", type: "goal", target: "box", position: { worldId: "inside-a", x: 3, y: 2 } },
    ],
    playerId: "player",
  },
] satisfies TutorialLevel[];

export const tutorialSolutions: Record<string, Direction[]> = {
  "tutorial-01-first-push": ["right", "right"],
  "tutorial-02-step-inside": ["right"],
  "tutorial-03-load-the-crate": ["right"],
  "tutorial-04-push-out": ["right"],
  "tutorial-05-two-layer-transfer": ["right", "right"],
  "tutorial-06-nested-cargo": ["right"],
  "tutorial-07-out-to-receiver": ["right"],
  "tutorial-08-chain-push": ["right", "right"],
  "tutorial-09-left-exit": ["left"],
  "tutorial-10-deep-entry": ["right", "right"],
  "tutorial-11-north-exit": ["up"],
  "tutorial-12-south-exit": ["down"],
  "tutorial-13-inside-to-outside": ["right", "right"],
  "tutorial-14-vertical-loader": ["right", "down"],
  "tutorial-15-deep-egress": ["right", "right", "right"],
};
