import type { Direction, LevelDefinition } from "../game";

export interface TutorialLevel extends LevelDefinition {
  lesson: string;
  subtitle: string;
  mechanicTags: string[];
  designIntent: string;
  parMoves: number;
  targetMoves: number;
  scriptedSolution: Direction[];
}

export const tutorialLevels = [
  {
    id: "tutorial-01-first-push",
    title: "First Push",
    lesson: "Push cargo into a powered dock.",
    subtitle: "Basic push discipline on a physical board.",
    mechanicTags: ["push", "dock"],
    designIntent: "Teach the baseline movement rule before any recursive space appears.",
    parMoves: 2,
    targetMoves: 2,
    scriptedSolution: ["right", "right"],
    worlds: [{ id: "root", name: "Root Bench", width: 6, height: 5 }],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "root", x: 2, y: 2 } },
      { id: "dock", type: "goal", target: "box", position: { worldId: "root", x: 4, y: 2 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-02-enter-box",
    title: "Glass Hatch",
    lesson: "Step into a crate that contains a room.",
    subtitle: "The crate window becomes the next playable plane.",
    mechanicTags: ["enter", "recursive-room"],
    designIntent: "Make entering a box the entire puzzle so the spatial contract is unmistakable.",
    parMoves: 1,
    targetMoves: 1,
    scriptedSolution: ["right"],
    worlds: [
      { id: "root", name: "Outer Plate", width: 5, height: 5 },
      {
        id: "inside-hatch",
        name: "Hatch Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "hatch" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "hatch",
        type: "box",
        name: "Glass Hatch",
        open: true,
        innerWorldId: "inside-hatch",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "arrival", type: "goal", target: "player", position: { worldId: "inside-hatch", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-03-eject-cargo",
    title: "Eject Cargo",
    lesson: "Push cargo out of a box into the parent world.",
    subtitle: "The edge of an inner room is also a door back out.",
    mechanicTags: ["push-out", "edge-exit"],
    designIntent: "Teach push-out from a contained room without another mechanic competing for attention.",
    parMoves: 1,
    targetMoves: 1,
    scriptedSolution: ["right"],
    worlds: [
      { id: "root", name: "Parent Rail", width: 5, height: 5 },
      {
        id: "inside-ejector",
        name: "Ejector Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "ejector" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "inside-ejector", x: 1, y: 1 } },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "inside-ejector", x: 2, y: 1 } },
      {
        id: "ejector",
        type: "box",
        name: "Ejector",
        open: true,
        innerWorldId: "inside-ejector",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "dock", type: "goal", target: "box", position: { worldId: "root", x: 3, y: 2 } },
    ],
    playerId: "player",
    activeWorldId: "inside-ejector",
  },
  {
    id: "tutorial-04-load-box",
    title: "Load the Hatch",
    lesson: "Push cargo into an open recursive box.",
    subtitle: "Cargo transfers to the room visible in the container window.",
    mechanicTags: ["push-into", "container"],
    designIntent: "Introduce push-into as the inverse of push-out using a straight rail.",
    parMoves: 1,
    targetMoves: 1,
    scriptedSolution: ["right"],
    worlds: [
      { id: "root", name: "Loading Rail", width: 5, height: 5 },
      {
        id: "inside-loader",
        name: "Loader Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "loader" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 0, y: 2 } },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "loader",
        type: "box",
        name: "Loader",
        open: true,
        innerWorldId: "inside-loader",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "dock", type: "goal", target: "box", position: { worldId: "inside-loader", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-05-inside-moves-outside",
    title: "Inside Moves Outside",
    lesson: "From inside a box, push a world-bearing module into the parent world.",
    subtitle: "An internal action relocates a visible outer object.",
    mechanicTags: ["push-out", "container", "parent-update"],
    designIntent: "Show that objects with their own interiors can move between parent and child spaces.",
    parMoves: 1,
    targetMoves: 1,
    scriptedSolution: ["right"],
    worlds: [
      { id: "root", name: "Outer Socket", width: 5, height: 5 },
      {
        id: "inside-carrier",
        name: "Carrier Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "carrier" },
        entry: { x: 1, y: 1 },
      },
      {
        id: "module-inner",
        name: "Module Core",
        width: 3,
        height: 3,
        parent: { worldId: "inside-carrier", boxId: "module" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "inside-carrier", x: 1, y: 1 } },
      {
        id: "module",
        type: "box",
        name: "World Module",
        innerWorldId: "module-inner",
        position: { worldId: "inside-carrier", x: 2, y: 1 },
      },
      {
        id: "carrier",
        type: "box",
        name: "Carrier",
        open: true,
        innerWorldId: "inside-carrier",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "dock", type: "goal", target: "box", position: { worldId: "root", x: 3, y: 2 } },
    ],
    playerId: "player",
    activeWorldId: "inside-carrier",
  },
  {
    id: "tutorial-06-two-layer-transfer",
    title: "Two-Layer Transfer",
    lesson: "Enter one box, then push cargo into a deeper box.",
    subtitle: "The second container sits inside the first room.",
    mechanicTags: ["enter", "push-into", "two-layer"],
    designIntent: "Combine entering a parent box with pushing cargo into a child box.",
    parMoves: 2,
    targetMoves: 2,
    scriptedSolution: ["right", "right"],
    worlds: [
      { id: "root", name: "Outer Rig", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "Fold A",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 2 },
      },
      {
        id: "inside-b",
        name: "Fold B",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-a",
        type: "box",
        name: "Fold A",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "inside-a", x: 2, y: 2 } },
      {
        id: "box-b",
        type: "box",
        name: "Fold B",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 3, y: 2 },
      },
      { id: "dock", type: "goal", target: "box", position: { worldId: "inside-b", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-07-cross-world-targets",
    title: "Cross-World Targets",
    lesson: "Complete goals in separate worlds at the same time.",
    subtitle: "The win check spans the root and an interior room.",
    mechanicTags: ["enter", "cross-world", "multi-goal"],
    designIntent: "Make it explicit that goals are not limited to the active world.",
    parMoves: 1,
    targetMoves: 1,
    scriptedSolution: ["right"],
    worlds: [
      { id: "root", name: "Twin Signal", width: 5, height: 5 },
      {
        id: "inside-signal",
        name: "Signal Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "signal-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "signal-box",
        type: "box",
        name: "Signal Box",
        open: true,
        innerWorldId: "inside-signal",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "parked-cargo", type: "box", name: "Parked Cargo", position: { worldId: "root", x: 0, y: 0 } },
      { id: "root-dock", type: "goal", target: "box", position: { worldId: "root", x: 0, y: 0 } },
      { id: "inner-dock", type: "goal", target: "player", position: { worldId: "inside-signal", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-08-enter-then-eject",
    title: "Enter, Then Eject",
    lesson: "Enter a box and push cargo back out to the root.",
    subtitle: "The correct move sequence crosses the same boundary twice.",
    mechanicTags: ["enter", "push-out", "sequence"],
    designIntent: "Require entering before a push-out can be made.",
    parMoves: 2,
    targetMoves: 2,
    scriptedSolution: ["right", "right"],
    worlds: [
      { id: "root", name: "Return Bench", width: 5, height: 5 },
      {
        id: "inside-return",
        name: "Return Interior",
        width: 3,
        height: 3,
        parent: { worldId: "root", boxId: "return-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "return-box",
        type: "box",
        name: "Return Box",
        open: true,
        innerWorldId: "inside-return",
        position: { worldId: "root", x: 2, y: 2 },
      },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "inside-return", x: 2, y: 1 } },
      { id: "dock", type: "goal", target: "box", position: { worldId: "root", x: 3, y: 2 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-09-nested-order",
    title: "Nested Order",
    lesson: "Enter a parent room before loading a world module into a dock.",
    subtitle: "The order matters: first access the room, then move the contained module.",
    mechanicTags: ["enter", "nested-box", "push-into"],
    designIntent: "Teach nested box ordering with a portable world-bearing crate.",
    parMoves: 2,
    targetMoves: 2,
    scriptedSolution: ["right", "right"],
    worlds: [
      { id: "root", name: "Order Gate", width: 5, height: 5 },
      {
        id: "inside-order",
        name: "Order Interior",
        width: 4,
        height: 5,
        parent: { worldId: "root", boxId: "order-box" },
        entry: { x: 0, y: 2 },
      },
      {
        id: "module-core",
        name: "Module Core",
        width: 3,
        height: 3,
        parent: { worldId: "inside-order", boxId: "module" },
        entry: { x: 1, y: 1 },
      },
      {
        id: "dock-core",
        name: "Dock Core",
        width: 3,
        height: 3,
        parent: { worldId: "inside-order", boxId: "dock-box" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "order-box",
        type: "box",
        name: "Order Box",
        open: true,
        innerWorldId: "inside-order",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "module",
        type: "box",
        name: "World Module",
        innerWorldId: "module-core",
        position: { worldId: "inside-order", x: 1, y: 2 },
      },
      {
        id: "dock-box",
        type: "box",
        name: "Dock Box",
        open: true,
        innerWorldId: "dock-core",
        position: { worldId: "inside-order", x: 2, y: 2 },
      },
      { id: "dock", type: "goal", target: "box", position: { worldId: "dock-core", x: 1, y: 1 } },
    ],
    playerId: "player",
  },
  {
    id: "tutorial-10-composite-fold",
    title: "Composite Fold",
    lesson: "Enter two layers and eject cargo from the deeper room.",
    subtitle: "A compact final check of entry, depth, and push-out.",
    mechanicTags: ["enter", "two-layer", "push-out", "composite"],
    designIntent: "Close the first set with the smallest puzzle that still feels recursive.",
    parMoves: 3,
    targetMoves: 3,
    scriptedSolution: ["right", "right", "right"],
    worlds: [
      { id: "root", name: "Composite Rig", width: 5, height: 5 },
      {
        id: "inside-a",
        name: "First Chamber",
        width: 5,
        height: 5,
        parent: { worldId: "root", boxId: "box-a" },
        entry: { x: 1, y: 2 },
      },
      {
        id: "inside-b",
        name: "Second Chamber",
        width: 3,
        height: 3,
        parent: { worldId: "inside-a", boxId: "box-b" },
        entry: { x: 1, y: 1 },
      },
    ],
    entities: [
      { id: "player", type: "player", position: { worldId: "root", x: 1, y: 2 } },
      {
        id: "box-a",
        type: "box",
        name: "First Chamber",
        open: true,
        innerWorldId: "inside-a",
        position: { worldId: "root", x: 2, y: 2 },
      },
      {
        id: "box-b",
        type: "box",
        name: "Second Chamber",
        open: true,
        innerWorldId: "inside-b",
        position: { worldId: "inside-a", x: 2, y: 2 },
      },
      { id: "cargo", type: "box", name: "Cargo", position: { worldId: "inside-b", x: 2, y: 1 } },
      { id: "dock", type: "goal", target: "box", position: { worldId: "inside-a", x: 3, y: 2 } },
    ],
    playerId: "player",
  },
] satisfies TutorialLevel[];

export const tutorialSolutions: Record<string, Direction[]> = Object.fromEntries(
  tutorialLevels.map((level) => [level.id, level.scriptedSolution]),
);
