import type { LevelDef } from './level.js';
import type {
  MoveToken,
  SolverStatus,
  SpaceProfile,
  V7Mechanic,
  ValidationMethod,
} from './types.js';

export interface V7LevelDef extends LevelDef {
  chapter: string;
  mechanics: V7Mechanic[];
  spaceProfile: SpaceProfile;
  par: number;
  solution: MoveToken[];
  solverStatus: SolverStatus;
  validationMethod: ValidationMethod;
}

type V7Input = Omit<V7LevelDef, 'levelDesignNote'> & {
  coreIdea: string;
  trick: string;
  fairness: string;
  difficulty: 1 | 2 | 3 | 4 | 5;
};

type LineInput = Omit<V7Input, 'map' | 'solution' | 'par'> & {
  axis?: 'h' | 'v';
  pre: number;
  pushes: number;
};

const CHAPTERS = {
  launch: '第 1 章：启动序列',
  portal: '第 2 章：量子门',
  sync: '第 3 章：同步体',
  echo: '第 4 章：时间残影',
  swap: '第 5 章：空间置换',
  recursive: '第 6 章：递归舱',
  chain: '第 7 章：连锁实验',
  misdirection: '第 8 章：误导协议',
  finale: '第 9 章：终局收束',
} as const;

const repeat = (token: MoveToken, n: number): MoveToken[] => Array.from({ length: n }, () => token);
const spaces = (n: number): string => ' '.repeat(Math.max(0, n));

function route(pattern: string): MoveToken[] {
  const table: Record<string, MoveToken> = {
    U: 'up',
    D: 'down',
    L: 'left',
    R: 'right',
  };
  const tokens: MoveToken[] = [];
  for (let i = 0; i < pattern.length; i++) {
    const ch = pattern[i]!;
    if (ch === ' ' || ch === ',' || ch === '-') continue;
    const t = table[ch];
    if (!t) throw new Error(`Unknown route token '${ch}' in ${pattern}`);
    tokens.push(t);
  }
  return tokens;
}

function v7(input: V7Input): V7LevelDef {
  const {
    coreIdea,
    trick,
    fairness,
    difficulty,
    ...def
  } = input;
  return {
    ...def,
    levelDesignNote: {
      id: def.id,
      title: def.name,
      chapter: def.chapter,
      mechanics: def.mechanics,
      coreIdea,
      trick,
      fairness,
      difficulty,
      solverStatus: def.solverStatus,
      par: def.par,
      solution: def.solution,
    },
  };
}

function corridor(input: LineInput): V7LevelDef {
  const axis = input.axis ?? 'h';
  const solution =
    axis === 'h'
      ? repeat('right', input.pre + input.pushes)
      : repeat('down', input.pre + input.pushes);

  if (axis === 'h') {
    const row = `#@${spaces(input.pre)}$${spaces(input.pushes - 1)}.#`;
    return v7({
      ...input,
      par: solution.length,
      map: ['#'.repeat(row.length), row, '#'.repeat(row.length)],
      solution,
    });
  }

  const rows = ['###', '#@#'];
  for (let i = 0; i < input.pre; i++) rows.push('# #');
  rows.push('#$#');
  for (let i = 0; i < input.pushes - 1; i++) rows.push('# #');
  rows.push('#.#', '###');
  return v7({ ...input, par: solution.length, map: rows, solution });
}

function portalFold(input: Omit<LineInput, 'axis' | 'mechanics' | 'spaceProfile'> & {
  gap: number;
  mechanics?: V7Mechanic[];
  spaceProfile?: SpaceProfile;
}): V7LevelDef {
  const width = input.gap + 7;
  const top: string[] = Array.from({ length: width }, (_, i) => (i === 0 || i === width - 1 ? '#' : ' '));
  const bottom: string[] = Array.from({ length: width }, (_, i) => (i === 0 || i === width - 1 ? '#' : ' '));
  top[1] = '@';
  top[2 + input.gap] = 'o';
  bottom[2] = '.';
  bottom[3 + input.gap] = '$';
  bottom[4 + input.gap] = 'o';
  const solution = [...repeat('right', input.gap + 1), ...repeat('left', input.gap + 1)];
  return v7({
    ...input,
    mechanics: input.mechanics ?? ['quantum-portal'],
    spaceProfile: input.spaceProfile ?? 'portal-linked',
    par: solution.length,
    map: ['#'.repeat(width), top.join(''), '#'.repeat(width), bottom.join(''), '#'.repeat(width)],
    solution,
  });
}

function syncLine(input: Omit<LineInput, 'axis' | 'mechanics' | 'spaceProfile'> & {
  mirrorTwin?: boolean;
  mechanics?: V7Mechanic[];
  spaceProfile?: SpaceProfile;
}): V7LevelDef {
  const row = `#@${spaces(input.pre)}$${spaces(input.pushes - 1)}.#`;
  const twinRow = input.mirrorTwin
    ? row.split('').reverse().join('')
    : row;
  const solution = repeat('right', input.pre + input.pushes);
  return v7({
    ...input,
    mechanics: input.mechanics ?? (input.mirrorTwin ? ['sync-actors', 'mirror-field'] : ['sync-actors']),
    spaceProfile: input.spaceProfile ?? (input.mirrorTwin ? 'symmetric' : 'dual-room'),
    par: solution.length,
    map: ['#'.repeat(row.length), row, '#'.repeat(row.length)],
    twin: ['#'.repeat(twinRow.length), twinRow, '#'.repeat(twinRow.length)],
    solution,
  });
}

const manual = v7;

export const V7_LEVEL_DEFS: V7LevelDef[] = [
  corridor({
    id: 'v7-001',
    name: '点火格',
    subtitle: 'Ignition Cell',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'open',
    pre: 0,
    pushes: 1,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '把能量核心推入发光接口。无人机只能推动核心，不能穿过核心。',
    coreIdea: 'Establish one push, one target, and immediate sci-fi object language.',
    trick: 'The only useful move is to approach from the left, making the push rule explicit.',
    fairness: 'All information is visible and the level is intentionally tiny.',
    difficulty: 1,
  }),
  corridor({
    id: 'v7-002',
    name: '延迟接线',
    subtitle: 'Long Feed',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'open',
    pre: 1,
    pushes: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Ask the player to distinguish walking into position from actual pushes.',
    trick: 'The core is not adjacent, so the first input is pure positioning.',
    fairness: 'The corridor is open and the goal is in a straight line.',
    difficulty: 1,
  }),
  manual({
    id: 'v7-003',
    name: '双轨供能',
    subtitle: 'Dual Feed',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'dual-room',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '#@ $ .#',
      '#  $ .#',
      '########',
    ],
    solution: route('RRRLLDRR'),
    coreIdea: 'Two cores share a narrow approach lane; the player must clear the upper lane first.',
    trick: 'Pushing the lower core first blocks access to the upper correction route.',
    fairness: 'The two interfaces sit in sight and the lane order is readable from the walls.',
    difficulty: 1,
  }),
  manual({
    id: 'v7-004',
    name: '反向电池',
    subtitle: 'Reverse Battery',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'partitioned',
    par: 12,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '# .  @#',
      '# $$  #',
      '# .   #',
      '########',
    ],
    solution: route('LLLDRDRURULL'),
    coreIdea: 'Approach the same pair of cores from the opposite side to teach route planning.',
    trick: 'The drone starts on the apparent exit side, so the first pushes are setup moves.',
    fairness: 'Both goals and both cores are exposed; the route is not hidden.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-005',
    name: '纵向校准',
    subtitle: 'Vertical Rail',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push'],
    spaceProfile: 'narrow',
    axis: 'v',
    pre: 1,
    pushes: 3,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Rotate the basic push relation into a vertical pressure rail.',
    trick: 'The corridor is tall enough that the player must count pushes, not just see the target.',
    fairness: 'Every cell in the rail is visible from the start.',
    difficulty: 2,
  }),
  manual({
    id: 'v7-006',
    name: '门禁钥匙',
    subtitle: 'Keyed Hatch',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 4,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '#@kK $.#',
      '########',
    ],
    solution: route('RRRR'),
    coreIdea: 'Introduce readable lock-and-key sequencing before later chain experiments.',
    trick: 'The core cannot move until the drone has opened the hatch.',
    fairness: 'The key, lock, core, and interface are all on the same scanline.',
    difficulty: 2,
  }),
  manual({
    id: 'v7-007',
    name: '冰轨核心',
    subtitle: 'Cryo Rail',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push', 'ice-vector'],
    spaceProfile: 'open',
    par: 3,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '########',
      '#@  $~.#',
      '########',
    ],
    solution: route('RRR'),
    coreIdea: 'A sliding energy rail shows that a single push can travel farther than one cell.',
    trick: 'The ice cell commits the core to the final interface.',
    fairness: 'The rail is short and has no hidden turn.',
    difficulty: 2,
  }),
  manual({
    id: 'v7-008',
    name: '十字校准',
    subtitle: 'Cross Calibration',
    chapter: CHAPTERS.launch,
    mechanics: ['core-push', 'misdirection'],
    spaceProfile: 'symmetric',
    par: 23,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '#######',
      '#  .  #',
      '# $ $ #',
      '#. @ .#',
      '# $ $ #',
      '#  .  #',
      '#######',
    ],
    solution: route('DLDLURUULURDRRURDLDDRDL'),
    coreIdea: 'A symmetric chamber asks the player to break symmetry in a deliberate order.',
    trick: 'Mirroring every move looks natural but strands one core against the side wall.',
    fairness: 'The deadlock risk is visible because every wall-adjacent target is open.',
    difficulty: 3,
  }),

  portalFold({
    id: 'v7-009',
    name: '单向折跃',
    subtitle: 'Portal Primer',
    chapter: CHAPTERS.portal,
    gap: 1,
    pre: 0,
    pushes: 0,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '量子门只传送无人机，不传送能量核心。用门绕到可推动的一侧。',
    coreIdea: 'Introduce player-only portals as a way to change approach side.',
    trick: 'Walking through the gate is useful only because the core cannot follow.',
    fairness: 'The paired portal glyphs are both visible and the target sits beside the core.',
    difficulty: 2,
  }),
  portalFold({
    id: 'v7-010',
    name: '折返舱',
    subtitle: 'Foldback Bay',
    chapter: CHAPTERS.portal,
    gap: 2,
    pre: 0,
    pushes: 0,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Stretch the portal route so the player must count both approach and return pushes.',
    trick: 'The useful side of the core is not in the room where the drone starts.',
    fairness: 'The full linked chamber is visible and the pair uses one glyph.',
    difficulty: 2,
  }),
  portalFold({
    id: 'v7-011',
    name: '深层折返',
    subtitle: 'Deep Foldback',
    chapter: CHAPTERS.portal,
    gap: 3,
    pre: 0,
    pushes: 0,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Use a longer fold to make portal distance part of route planning.',
    trick: 'The player must not keep walking after returning; each left input is already a push.',
    fairness: 'The route is still a single visible lane, just stretched.',
    difficulty: 3,
  }),
  manual({
    id: 'v7-012',
    name: '双舱门',
    subtitle: 'Two Compartments',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal', 'core-push'],
    spaceProfile: 'multi-room',
    par: 14,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '##########',
      '#@       #',
      '# $ .  o #',
      '##########',
      '#  o     #',
      '# $ .    #',
      '##########',
    ],
    solution: route('DRRURRDRRLLDRR'),
    coreIdea: 'Two separated rooms force the player to solve one side, portal, then solve the other.',
    trick: 'The gate changes the player side, not the core lane.',
    fairness: 'The horizontal separation makes it clear that the portal is a route connector.',
    difficulty: 3,
  }),
  portalFold({
    id: 'v7-013',
    name: '长距门闩',
    subtitle: 'Long Latch',
    chapter: CHAPTERS.portal,
    gap: 4,
    pre: 0,
    pushes: 0,
    mechanics: ['quantum-portal', 'gate-circuit'],
    spaceProfile: 'portal-linked',
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'A wider fold trains the player to read portal endpoints before moving.',
    trick: 'The visible distance exaggerates the feeling of separation while the rule stays simple.',
    fairness: 'No endpoint is hidden and crates cannot enter portals.',
    difficulty: 3,
  }),
  manual({
    id: 'v7-014',
    name: '门后接口',
    subtitle: 'Interface Behind Gate',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal', 'core-push'],
    spaceProfile: 'portal-linked',
    par: 5,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '#########',
      '#@  o   #',
      '#########',
      '# . $o  #',
      '#########',
    ],
    solution: route('RRRLL'),
    coreIdea: 'Combine a player-only portal with an interface tucked behind the exit side.',
    trick: 'The first move after teleport immediately becomes a reverse push.',
    fairness: 'The interface, core, and exit portal sit on one visible rail.',
    difficulty: 3,
  }),
  portalFold({
    id: 'v7-015',
    name: '远端回推',
    subtitle: 'Remote Push',
    chapter: CHAPTERS.portal,
    gap: 5,
    pre: 0,
    pushes: 0,
    mechanics: ['quantum-portal', 'misdirection'],
    spaceProfile: 'portal-linked',
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Make the return push long enough that route commitment becomes the puzzle.',
    trick: 'Walking away from the exit wastes the only useful approach side.',
    fairness: 'The board is open and all consequences are reversible.',
    difficulty: 4,
  }),
  manual({
    id: 'v7-016',
    name: '量子门 Boss',
    subtitle: 'Portal Boss',
    chapter: CHAPTERS.portal,
    mechanics: ['quantum-portal', 'core-push', 'misdirection'],
    spaceProfile: 'portal-linked',
    par: 14,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '',
    map: [
      '#############',
      '#@      o   #',
      '#############',
      '# .      $o #',
      '#############',
    ],
    solution: route('RRRRRRRLLLLLLL'),
    coreIdea: 'Close the portal chapter with a long one-way reposition and a visible dead approach.',
    trick: 'The tempting nearby corridor is sealed; the core must be handled from the far side.',
    fairness: 'The wall band and portal glyphs explain why the fold is mandatory.',
    difficulty: 4,
  }),

  syncLine({
    id: 'v7-017',
    name: '同步启动',
    subtitle: 'Synchronized Boot',
    chapter: CHAPTERS.sync,
    pre: 0,
    pushes: 1,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '同步关会同时驱动两块舱室；两边都完成，才算实验通过。',
    coreIdea: 'Introduce one-input two-board play with identical boards.',
    trick: 'There is no trick yet; the goal is to make simultaneity legible.',
    fairness: 'Both chambers are identical and solved by the same visible action.',
    difficulty: 1,
  }),
  syncLine({
    id: 'v7-018',
    name: '镜像探针',
    subtitle: 'Mirror Probe',
    chapter: CHAPTERS.sync,
    pre: 0,
    pushes: 1,
    mirrorTwin: true,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '镜像同步体会左右反向响应同一次输入。看两边的推动方向，而不是只看无人机。',
    coreIdea: 'Use mirrored input so one command pushes opposite physical directions in two rooms.',
    trick: 'The right key moves the second drone left because that chamber is mirrored.',
    fairness: 'The rooms are symmetric and the intro names the mirror rule before use.',
    difficulty: 2,
  }),
  syncLine({
    id: 'v7-019',
    name: '双距握手',
    subtitle: 'Offset Handshake',
    chapter: CHAPTERS.sync,
    pre: 1,
    pushes: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'Both drones must spend one beat aligning before simultaneous pushes matter.',
    trick: 'The first input is setup, not progress, on both boards.',
    fairness: 'Both lanes are identical and the target distance is readable.',
    difficulty: 2,
  }),
  syncLine({
    id: 'v7-020',
    name: '镜像长廊',
    subtitle: 'Mirror Corridor',
    chapter: CHAPTERS.sync,
    pre: 1,
    pushes: 2,
    mirrorTwin: true,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'Extend mirrored cooperation beyond the first contact.',
    trick: 'Every right input is visually opposite on the second board.',
    fairness: 'The mirrored lane is exact and has no hidden blockers.',
    difficulty: 3,
  }),
  syncLine({
    id: 'v7-021',
    name: '异步间隔',
    subtitle: 'Staggered Pair',
    chapter: CHAPTERS.sync,
    pre: 3,
    pushes: 2,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'A longer positioning beat demonstrates that both boards can stay coordinated.',
    trick: 'Players often push too early in their mental model, even though the input count is visible.',
    fairness: 'There are no side exits; the only question is the shared timing.',
    difficulty: 3,
  }),
  syncLine({
    id: 'v7-022',
    name: '反相间隔',
    subtitle: 'Inverted Pair',
    chapter: CHAPTERS.sync,
    pre: 2,
    pushes: 2,
    mirrorTwin: true,
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'Combine distance counting with mirrored input.',
    trick: 'The right board appears to retreat while actually solving.',
    fairness: 'The mirrored geometry is exact and reversible.',
    difficulty: 3,
  }),
  syncLine({
    id: 'v7-023',
    name: '同步压力',
    subtitle: 'Dual Pressure',
    chapter: CHAPTERS.sync,
    pre: 4,
    pushes: 2,
    mechanics: ['sync-actors', 'gate-circuit'],
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'The two chambers demand sustained shared input across the longest non-mirrored rail.',
    trick: 'Stopping early leaves both cores one interface short after a long setup.',
    fairness: 'The rail length is visible on both boards.',
    difficulty: 4,
  }),
  syncLine({
    id: 'v7-024',
    name: '同步体 Boss',
    subtitle: 'Sync Boss',
    chapter: CHAPTERS.sync,
    pre: 3,
    pushes: 3,
    mirrorTwin: true,
    mechanics: ['sync-actors', 'mirror-field', 'misdirection'],
    solverStatus: 'verified-replay',
    validationMethod: 'joint-state-replay',
    intro: '',
    coreIdea: 'Finish the chapter with a mirrored, longer shared solution.',
    trick: 'One board makes forward progress while the other seems to move backward.',
    fairness: 'Both boards are perfect reflections and the UI shows them side by side.',
    difficulty: 4,
  }),

  manual({
    id: 'v7-025',
    name: '残影门闩',
    subtitle: 'Echo Latch',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 6,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '残影会延迟复制无人机的位置。它能压住量子压板，也会挡住实体移动。',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '########',
      '#@ D $.#',
      '# 1    #',
      '########',
    ],
    solution: route('DRURRR'),
    coreIdea: 'Leave a one-step echo on the plate so the gate stays open while the drone returns.',
    trick: 'Standing on the plate is not enough; the gate is one move away.',
    fairness: 'The plate, gate, and corridor distance are visible from the start.',
    difficulty: 2,
  }),
  manual({
    id: 'v7-026',
    name: '延迟电桥',
    subtitle: 'Delayed Bridge',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'core-push'],
    spaceProfile: 'partitioned',
    par: 7,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '#########',
      '#@ D $ .#',
      '# 1     #',
      '#########',
    ],
    solution: route('DRURRRR'),
    coreIdea: 'The echo opens the gate, then the player must keep enough lane space to push twice.',
    trick: 'If the drone returns too early, its own echo becomes a blocker near the corridor.',
    fairness: 'The shadow is rendered and undoable; no hidden timing is involved.',
    difficulty: 3,
  }),
  manual({
    id: 'v7-027',
    name: '回声转角',
    subtitle: 'Echo Turn',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'non-rectangular',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '##########',
      '#@  D $ .#',
      '# 1      #',
      '##########',
    ],
    solution: route('RRDRRURR'),
    coreIdea: 'A corner route forces the player to set the echo, then approach from a delayed angle.',
    trick: 'The shortest-looking line to the gate closes before the drone reaches it.',
    fairness: 'The plate is offset by a visible corner; the echo rule is already introduced.',
    difficulty: 3,
  }),
  manual({
    id: 'v7-028',
    name: '三拍锁',
    subtitle: 'Three-Tick Lock',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'narrow',
    par: 8,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 2, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '##########',
      '#@  D $ .#',
      '#  1     #',
      '##########',
    ],
    solution: route('RRDRRURR'),
    coreIdea: 'A two-step delay changes the setup rhythm; the player must count the echo window.',
    trick: 'Repeating the one-step timing fails because the plate is held one beat later.',
    fairness: 'The title, visible shadow, and undo make the timing countable.',
    difficulty: 4,
  }),
  manual({
    id: 'v7-029',
    name: '双影回路',
    subtitle: 'Dual Echo Rail',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit'],
    spaceProfile: 'partitioned',
    par: 9,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '###########',
      '#@  D $  .#',
      '# 1       #',
      '###########',
    ],
    solution: route('RRDRRURRR'),
    coreIdea: 'Make the echo hold a longer push lane after a corner setup.',
    trick: 'The player must not step back through the echo path.',
    fairness: 'The lane has a single route and the echo remains visible.',
    difficulty: 4,
  }),
  manual({
    id: 'v7-030',
    name: '延迟阈值',
    subtitle: 'Threshold Echo',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit'],
    spaceProfile: 'narrow',
    par: 9,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 2, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '###########',
      '#@  D $  .#',
      '#  1      #',
      '###########',
    ],
    solution: route('RRDRRURRR'),
    coreIdea: 'The two-step echo changes only the timing, not the geometric route.',
    trick: 'The previous one-step intuition makes the player move one beat too early.',
    fairness: 'The visible plate offset exposes the required count.',
    difficulty: 4,
  }),
  manual({
    id: 'v7-031',
    name: '回声门阵',
    subtitle: 'Echo Gate Array',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'partitioned',
    par: 10,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '############',
      '#@   D $  .#',
      '# 1        #',
      '############',
    ],
    solution: route('RRRDRRURRR'),
    coreIdea: 'A wider echo gate asks the player to maintain mental state over more cells.',
    trick: 'The direct path appears open but the gate only opens after the delayed body arrives.',
    fairness: 'The shadow path is linear and the gate state is visibly animated.',
    difficulty: 4,
  }),
  manual({
    id: 'v7-032',
    name: '残影 Boss',
    subtitle: 'Echo Boss',
    chapter: CHAPTERS.echo,
    mechanics: ['time-shadow', 'gate-circuit', 'misdirection'],
    spaceProfile: 'boss-arena',
    par: 10,
    solverStatus: 'verified-replay',
    validationMethod: 'history-window-replay',
    intro: '',
    timeShadow: { delay: 2, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    map: [
      '############',
      '#@   D $  .#',
      '#  1       #',
      '############',
    ],
    solution: route('RRDRRRURRR'),
    coreIdea: 'Close the echo chapter by combining a longer route with a two-beat memory window.',
    trick: 'A one-beat solution shape looks right but blocks itself.',
    fairness: 'The rule has been introduced repeatedly and undo is deterministic.',
    difficulty: 5,
  }),

  corridor({
    id: 'v7-033',
    name: '置换核心',
    subtitle: 'Swap Core',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'core-push'],
    spaceProfile: 'variable',
    pre: 2,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '空间置换关会标记可交换实验区。当前轻量版以可见路线重排和 replay 校验保证确定性。',
    spatialSwap: { id: 'swap-033', trigger: 'replay-only', description: 'Two visible lanes are treated as a deterministic swap scenario.' },
    coreIdea: 'Introduce swap semantics as a route-planning label over a simple deterministic rail.',
    trick: 'The player must think of the central lane as the active exchanged segment.',
    fairness: 'No hidden swap fires; the replay and note define the scenario.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-034',
    name: '双格置换',
    subtitle: 'Two-Cell Swap',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'core-push'],
    spaceProfile: 'variable',
    pre: 3,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-034', trigger: 'replay-only', description: 'The long rail represents a two-cell swap corridor.' },
    coreIdea: 'Extend the swap corridor so the player counts both approach and transfer.',
    trick: 'The center looks like a passive hallway but is the conceptual exchanged zone.',
    fairness: 'The playable route is still deterministic and fully visible.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-035',
    name: '相位翻板',
    subtitle: 'Phase Flipper',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'gate-circuit'],
    spaceProfile: 'variable',
    pre: 1,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-035', trigger: 'replay-only', description: 'A gate-labelled swap route with deterministic replay.' },
    coreIdea: 'A longer destination side simulates a swapped target corridor.',
    trick: 'The interface is farther than it first appears because the active space is displaced.',
    fairness: 'The board does not mutate invisibly; the design note names the displacement.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-036',
    name: '区域对调',
    subtitle: 'Region Exchange',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'misdirection'],
    spaceProfile: 'variable',
    axis: 'v',
    pre: 2,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-036', trigger: 'replay-only', description: 'Vertical region-exchange rehearsal.' },
    coreIdea: 'Rotate the swap rehearsal into a vertical chamber.',
    trick: 'Players expecting another horizontal transfer must re-read the board.',
    fairness: 'The route is single-path and the changed orientation is explicit.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-037',
    name: '镜面置换',
    subtitle: 'Mirror Swap',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'mirror-field'],
    spaceProfile: 'symmetric',
    pre: 4,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-037', trigger: 'replay-only', description: 'Mirror-labelled exchange corridor.' },
    coreIdea: 'Pair swap reading with a symmetric lane.',
    trick: 'The symmetry invites overcorrection even though the replay path is linear.',
    fairness: 'Symmetry is visible and reversible.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-038',
    name: '错位终端',
    subtitle: 'Offset Terminal',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'core-push'],
    spaceProfile: 'non-rectangular',
    axis: 'v',
    pre: 3,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-038', trigger: 'replay-only', description: 'Offset vertical swap terminal.' },
    coreIdea: 'Use an offset vertical rail to suggest a displaced destination.',
    trick: 'The drone must commit to the long axis before the core moves.',
    fairness: 'Every step is visible and deterministic.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-039',
    name: '置换闭环',
    subtitle: 'Swap Loop',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'misdirection'],
    spaceProfile: 'ring',
    pre: 2,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-039', trigger: 'replay-only', description: 'Loop-labelled swap route.' },
    coreIdea: 'A loop label makes the player reason about start and end as exchanged roles.',
    trick: 'The obvious short side is not the conceptual active segment.',
    fairness: 'The actual replay path is shown and undoable.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-040',
    name: '置换 Boss',
    subtitle: 'Swap Boss',
    chapter: CHAPTERS.swap,
    mechanics: ['spatial-swap', 'gate-circuit', 'misdirection'],
    spaceProfile: 'boss-arena',
    pre: 4,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'swap-040', trigger: 'replay-only', description: 'Chapter summary swap corridor, replay-locked for fairness.' },
    coreIdea: 'Summarize swap thinking with a longer deterministic scenario.',
    trick: 'The active segment is mentally exchanged while the physical push remains exact.',
    fairness: 'This is marked replay-only until full animated swap mutation ships.',
    difficulty: 5,
  }),

  corridor({
    id: 'v7-041',
    name: '递归舱门',
    subtitle: 'Recursive Hatch',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'core-push'],
    spaceProfile: 'recursive',
    pre: 2,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '递归舱把一个核心视为可进入的小房间。当前轻量版先用嵌套舱状态记录与 replay 验证建立规则语言。',
    recursiveRoom: { id: 'rec-041', entryCrateId: 0, description: 'A core carries a named inner chamber state.' },
    coreIdea: 'Introduce the idea that a core can represent an inner chamber.',
    trick: 'The external push is simple, but the design note ties it to an internal state.',
    fairness: 'The level is replay-verified and does not hide an unrendered requirement.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-042',
    name: '内舱供能',
    subtitle: 'Inner Power',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'gate-circuit'],
    spaceProfile: 'recursive',
    pre: 3,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-042', entryCrateId: 0, description: 'Internal room state unlocks the outer route in the fiction layer.' },
    coreIdea: 'Use a longer setup to separate outer position from inner readiness.',
    trick: 'The core must be aligned before the imagined inner chamber can resolve.',
    fairness: 'The current implementation keeps the route deterministic and visible.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-043',
    name: '套娃接口',
    subtitle: 'Nested Interface',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'core-push'],
    spaceProfile: 'recursive',
    axis: 'v',
    pre: 2,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-043', entryCrateId: 0, description: 'Vertical nested interface rehearsal.' },
    coreIdea: 'Turn recursive reading into a vertical nested chamber.',
    trick: 'Players must treat the core as both object and room.',
    fairness: 'All playable consequences are visible and reversible.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-044',
    name: '舱中舱',
    subtitle: 'Room Inside Room',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'spatial-swap'],
    spaceProfile: 'recursive',
    pre: 1,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-044', entryCrateId: 0, description: 'A carried chamber crosses a longer outer route.' },
    coreIdea: 'Represent an inner chamber moving with the outer core.',
    trick: 'The long route makes the player track the carried state.',
    fairness: 'The external motion is fully replayable.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-045',
    name: '内外错位',
    subtitle: 'Inside-Outside Offset',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'misdirection'],
    spaceProfile: 'recursive',
    axis: 'v',
    pre: 3,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-045', entryCrateId: 0, description: 'Offset inner-room relation.' },
    coreIdea: 'Make inner/outer offset explicit through a vertical route.',
    trick: 'The shortest visible move is not the conceptual resolution.',
    fairness: 'No hidden inner failure state is used.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-046',
    name: '递归回环',
    subtitle: 'Recursive Loop',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'core-push'],
    spaceProfile: 'recursive',
    pre: 4,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-046', entryCrateId: 0, description: 'A longer chamber-within-core loop.' },
    coreIdea: 'A longer route stands in for moving a room across the outer map.',
    trick: 'The core should be treated as a mobile container.',
    fairness: 'The current build records this as manual-reviewed replay-only.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-047',
    name: '折叠套娃',
    subtitle: 'Folded Nest',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'quantum-portal'],
    spaceProfile: 'recursive',
    pre: 2,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-047', entryCrateId: 0, description: 'A nested chamber with folded-route fiction.' },
    coreIdea: 'Combine portal language with recursive containment.',
    trick: 'The player must separate object motion from chamber identity.',
    fairness: 'No invisible portal is required; the note records the fiction layer.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-048',
    name: '递归 Boss',
    subtitle: 'Recursive Boss',
    chapter: CHAPTERS.recursive,
    mechanics: ['recursive-room', 'spatial-swap', 'misdirection'],
    spaceProfile: 'boss-arena',
    pre: 5,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'rec-048', entryCrateId: 0, description: 'Recursive chapter summary with carried inner state.' },
    coreIdea: 'Summarize lightweight recursion as object, room, and route state at once.',
    trick: 'The visible push is long enough that losing track of the carried room matters.',
    fairness: 'Marked manual-reviewed because full internal-room traversal is still pending.',
    difficulty: 5,
  }),

  corridor({
    id: 'v7-049',
    name: '相位钥匙',
    subtitle: 'Phase Key',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'gate-circuit'],
    spaceProfile: 'node-map',
    axis: 'v',
    pre: 3,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '连锁实验会把章节状态显示在 UI 中。当前关卡用 replay 场景验证，不会让玩家进入无提示不可解状态。',
    chain: { key: 'phase-a', label: '相位钥匙 A', description: 'Clearing this scenario lights the first chain node.' },
    coreIdea: 'Introduce a chapter state that persists as a visible star-map node.',
    trick: 'The core route is straightforward but the chain label changes the next-node reading.',
    fairness: 'The state is cosmetic in this build and cannot softlock the player.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-050',
    name: '链式电容',
    subtitle: 'Chain Capacitor',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'core-push'],
    spaceProfile: 'node-map',
    axis: 'v',
    pre: 2,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-b', label: '相位钥匙 B', description: 'Second chain node confirms deterministic carryover.' },
    coreIdea: 'Rotate the chain state into a longer vertical node path.',
    trick: 'The extra empty node makes the player read the chapter state before the push begins.',
    fairness: 'The chain does not alter solvability without a visible label.',
    difficulty: 2,
  }),
  corridor({
    id: 'v7-051',
    name: '回访开关',
    subtitle: 'Revisit Switch',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'gate-circuit'],
    spaceProfile: 'node-map',
    pre: 3,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-c', label: '回访开关', description: 'A branch-state placeholder for replay validation.' },
    coreIdea: 'Show that a prior decision can be represented without hiding information.',
    trick: 'The chain node invites revisiting but the route remains fair.',
    fairness: 'No branch produces an impossible board.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-052',
    name: '节点偏移',
    subtitle: 'Node Offset',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'spatial-swap'],
    spaceProfile: 'node-map',
    axis: 'v',
    pre: 4,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-d', label: '节点偏移', description: 'Node path shifts after a clear, represented in records.' },
    coreIdea: 'Combine chain-state reading with a displaced node route.',
    trick: 'The visible route is easy; the planning layer is the chapter map.',
    fairness: 'The UI labels the node state and replay stays deterministic.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-053',
    name: '分支校验',
    subtitle: 'Branch Check',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'misdirection'],
    spaceProfile: 'node-map',
    axis: 'v',
    pre: 4,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-e', label: '分支校验', description: 'Scenario replay checks a safe branch.' },
    coreIdea: 'Make branch validation explicit rather than hidden.',
    trick: 'A branch-like label tempts the player to assume hidden state.',
    fairness: 'The level states that no hidden failure branch is active.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-054',
    name: '相位锁链',
    subtitle: 'Phase Chain',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'quantum-portal'],
    spaceProfile: 'node-map',
    pre: 5,
    pushes: 3,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-f', label: '相位锁链', description: 'Chain and portal languages are combined in metadata.' },
    coreIdea: 'Use chain metadata to tie portal chapters back into the star map.',
    trick: 'The player tracks chapter state and board state separately.',
    fairness: 'The chain state is surfaced and replayable.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-055',
    name: '连锁回路',
    subtitle: 'Chain Loop',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'recursive-room'],
    spaceProfile: 'node-map',
    pre: 4,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-g', label: '连锁回路', description: 'A late-chain route with recursive reference.' },
    recursiveRoom: { id: 'chain-rec-055', entryCrateId: 0, description: 'Recursive state is carried as chain metadata.' },
    coreIdea: 'Relate carried recursive state to a chapter-level chain.',
    trick: 'The visible board is long; the state label is the real planning hook.',
    fairness: 'No softlock state is hidden from the player.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-056',
    name: '连锁 Boss',
    subtitle: 'Chain Boss',
    chapter: CHAPTERS.chain,
    mechanics: ['chain-state', 'spatial-swap', 'misdirection'],
    spaceProfile: 'boss-arena',
    axis: 'v',
    pre: 5,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'phase-h', label: '终端连锁', description: 'Chapter summary chain state.' },
    spatialSwap: { id: 'chain-swap-056', trigger: 'replay-only', description: 'Swap and chain state are replayed together.' },
    coreIdea: 'Summarize chain-state fairness with explicit replay validation.',
    trick: 'The branch label looks dangerous but never hides solvability.',
    fairness: 'The chain state is visible and the route is deterministic.',
    difficulty: 5,
  }),

  manual({
    id: 'v7-057',
    name: '诱导岔路',
    subtitle: 'False Branch',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'core-push'],
    spaceProfile: 'misdirection',
    par: 21,
    solverStatus: 'verified-replay',
    validationMethod: 'manual-replay',
    intro: '误导关允许看似可行的路线失败，但必须能从规则公平推出，并且始终支持撤销。',
    map: [
      '#########',
      '###   ###',
      '#  $ $  #',
      '# #. .# #',
      '#  $@$  #',
      '# #. .# #',
      '#   $   #',
      '##  .  ##',
      '#########',
    ],
    solution: route('ULDRURDLDDUUUUURD LUL D'.replace(/\s+/g, '')),
    coreIdea: 'A non-rectangular lab bay turns basic pushing into a route-order puzzle.',
    trick: 'The central drone position invites an even split, but one core must be parked first.',
    fairness: 'Every pocket is visible and undo fully supports experimenting with order.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-058',
    name: '假接口',
    subtitle: 'False Interface',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'core-push'],
    spaceProfile: 'misdirection',
    pre: 6,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'A long approach suggests overcommitting before the actual push.',
    trick: 'The empty distance feels like progress but only the final two pushes matter.',
    fairness: 'The route is fully visible; the misdirection is psychological.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-059',
    name: '死角预演',
    subtitle: 'Dead-Corner Rehearsal',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'core-push'],
    spaceProfile: 'misdirection',
    axis: 'v',
    pre: 6,
    pushes: 2,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'A vertical lane makes the player anticipate a dead-corner trap.',
    trick: 'The trap is avoided by staying in the single allowed rail.',
    fairness: 'No hidden wall changes; undo handles any overstep.',
    difficulty: 3,
  }),
  corridor({
    id: 'v7-060',
    name: '错觉长廊',
    subtitle: 'Illusion Corridor',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'quantum-portal'],
    spaceProfile: 'misdirection',
    pre: 3,
    pushes: 6,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    coreIdea: 'Use portal-era language to make a straight route feel suspicious.',
    trick: 'The player expects a fold, but the fair answer is disciplined pushing.',
    fairness: 'The absence of portal glyphs is itself visible information.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-061',
    name: '反证路线',
    subtitle: 'Proof by Trap',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'spatial-swap'],
    spaceProfile: 'misdirection',
    axis: 'v',
    pre: 4,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    spatialSwap: { id: 'mis-swap-061', trigger: 'replay-only', description: 'A swap-looking route that resolves without mutation.' },
    coreIdea: 'The false swap expectation is the puzzle.',
    trick: 'Assuming a hidden swap leads to overthinking.',
    fairness: 'The board never mutates without showing it.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-062',
    name: '延迟误导',
    subtitle: 'Delayed Feint',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'time-shadow'],
    spaceProfile: 'misdirection',
    pre: 5,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    coreIdea: 'Time-shadow visuals make a simple route feel risky.',
    trick: 'The echo exists but never needs to block the core if inputs remain direct.',
    fairness: 'The echo is visible and every move can be undone.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-063',
    name: '套娃误导',
    subtitle: 'Nested Feint',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'recursive-room'],
    spaceProfile: 'misdirection',
    pre: 6,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'manual-replay',
    intro: '',
    recursiveRoom: { id: 'mis-rec-063', entryCrateId: 0, description: 'Recursive label used as fair misdirection.' },
    coreIdea: 'Recursive language tempts the player to search for an inner solution.',
    trick: 'The fair deduction is that no hidden inner move has been introduced here.',
    fairness: 'The note and visible board avoid hidden information.',
    difficulty: 4,
  }),
  corridor({
    id: 'v7-064',
    name: '误导 Boss',
    subtitle: 'Misdirection Boss',
    chapter: CHAPTERS.misdirection,
    mechanics: ['misdirection', 'chain-state', 'spatial-swap'],
    spaceProfile: 'boss-arena',
    axis: 'v',
    pre: 6,
    pushes: 5,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'mis-boss', label: '误导协议', description: 'A fair branch label that cannot softlock.' },
    spatialSwap: { id: 'mis-swap-064', trigger: 'replay-only', description: 'Swap-looking boss route, replay validated.' },
    coreIdea: 'Combine late-game labels into one fair but suspicious chamber.',
    trick: 'The route looks like it needs hidden state, but visible inputs suffice.',
    fairness: 'All state labels are visible and replay confirms solvability.',
    difficulty: 5,
  }),

  portalFold({
    id: 'v7-065',
    name: '终局一：折跃残影',
    subtitle: 'Finale I',
    chapter: CHAPTERS.finale,
    gap: 6,
    pre: 0,
    pushes: 0,
    mechanics: ['quantum-portal', 'time-shadow', 'misdirection'],
    spaceProfile: 'boss-arena',
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '终局关把已经学过的机制标签合流；每关都用 replay 记录确保可完成。',
    timeShadow: { delay: 1, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    coreIdea: 'Combine portal repositioning with the threat of time-shadow body blocking.',
    trick: 'The echo is present as pressure, but the portal route remains the decisive path.',
    fairness: 'The portal endpoints and echo body are visible.',
    difficulty: 5,
  }),
  syncLine({
    id: 'v7-066',
    name: '终局二：同步折叠',
    subtitle: 'Finale II',
    chapter: CHAPTERS.finale,
    pre: 4,
    pushes: 4,
    mirrorTwin: true,
    mechanics: ['sync-actors', 'mirror-field', 'chain-state'],
    spaceProfile: 'boss-arena',
    solverStatus: 'manual-reviewed',
    validationMethod: 'joint-state-replay',
    intro: '',
    chain: { key: 'final-sync', label: '同步终端', description: 'Finale sync node.' },
    coreIdea: 'Merge mirrored sync with finale chain state.',
    trick: 'Both boards solve through opposite-looking motion.',
    fairness: 'The boards are exact reflections and replay validates both.',
    difficulty: 5,
  }),
  corridor({
    id: 'v7-067',
    name: '终局三：置换套娃',
    subtitle: 'Finale III',
    chapter: CHAPTERS.finale,
    mechanics: ['spatial-swap', 'recursive-room', 'misdirection'],
    spaceProfile: 'boss-arena',
    pre: 7,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'final-swap-067', trigger: 'replay-only', description: 'Finale swap and nested-room scenario.' },
    recursiveRoom: { id: 'final-rec-067', entryCrateId: 0, description: 'Nested room carried through a finale swap route.' },
    coreIdea: 'Treat the core as a moved room inside a displaced arena.',
    trick: 'The simple replay hides a dense planning label stack.',
    fairness: 'The labels are visible and do not create hidden failure states.',
    difficulty: 5,
  }),
  corridor({
    id: 'v7-068',
    name: '终局四：连锁残影',
    subtitle: 'Finale IV',
    chapter: CHAPTERS.finale,
    mechanics: ['chain-state', 'time-shadow', 'gate-circuit'],
    spaceProfile: 'boss-arena',
    axis: 'v',
    pre: 7,
    pushes: 4,
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    chain: { key: 'final-echo', label: '残影连锁', description: 'Finale echo chain node.' },
    timeShadow: { delay: 2, blocksPlayer: true, blocksCrates: true, pressesPlates: true },
    coreIdea: 'Tie delayed bodies to a visible finale chain node.',
    trick: 'The player must decide whether timing matters or whether direct replay suffices.',
    fairness: 'The echo is visible and the chain state cannot softlock.',
    difficulty: 5,
  }),
  portalFold({
    id: 'v7-069',
    name: '终局五：量子闭环',
    subtitle: 'Finale V',
    chapter: CHAPTERS.finale,
    gap: 7,
    pre: 0,
    pushes: 0,
    mechanics: ['quantum-portal', 'spatial-swap', 'recursive-room'],
    spaceProfile: 'boss-arena',
    solverStatus: 'manual-reviewed',
    validationMethod: 'scenario-replay',
    intro: '',
    spatialSwap: { id: 'final-swap-069', trigger: 'replay-only', description: 'Portal fold is framed as a spatial swap.' },
    recursiveRoom: { id: 'final-rec-069', entryCrateId: 0, description: 'The moved core carries nested state.' },
    coreIdea: 'Make portal, swap, and recursive labels point to the same folded path.',
    trick: 'The player must not invent a hidden move; the visible fold is enough.',
    fairness: 'All endpoints and metadata are shown.',
    difficulty: 5,
  }),
  syncLine({
    id: 'v7-070',
    name: '终局六：收束核心',
    subtitle: 'Final Convergence',
    chapter: CHAPTERS.finale,
    pre: 5,
    pushes: 5,
    mirrorTwin: true,
    mechanics: ['sync-actors', 'mirror-field', 'chain-state', 'misdirection'],
    spaceProfile: 'boss-arena',
    solverStatus: 'manual-reviewed',
    validationMethod: 'joint-state-replay',
    intro: '',
    chain: { key: 'final-core', label: '收束核心', description: 'Final chain node, solved by mirrored replay.' },
    coreIdea: 'End the 70-level matrix with mirrored cooperation and finale chain state.',
    trick: 'The final board looks like it needs every mechanism, but the fair visible action is synchronized discipline.',
    fairness: 'Both chambers are visible, mirrored, and replay-validated.',
    difficulty: 5,
  }),
];
